trigger:
- none

name: Azure Pipelines

variables:
  python.version: '3.7.6'
  terraform.version: '0.13.4'

stages:
- stage: Provisioning
  displayName: Infra Provisioning
  jobs:
    - job: ProvisioningAppService
      displayName: Provisioning AppService
      steps:
        - task: InstallSSHKey@0
          inputs:
            knownHostsEntry: 'default'
            sshKeySecureFile: 'id_rsa'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              'ls /home/vsts/work/_temp/'
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'Azure subscription 1(f8815ca1-2653-4eca-b987-4de651bf2b5c)'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              call az storage account create --name $(terraformstorageaccount) --resource-group $(terraformstoragerg) --location eastus --sku Standard_LRS
              call az storage container create --name terraform --account-name $(terraformstorageaccount)         
              call az storage account keys list -g $(terraformstoragerg) -n $(terraformstorageaccount)


